# Generated by Django 2.2.3 on 2019-09-08 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(default='match', max_length=256, unique=True)),
                ('match_start_time', models.CharField(max_length=256)),
                ('match_end_time', models.CharField(max_length=256)),
                ('match_frags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=256, unique=True)),
                ('player_email', models.CharField(max_length=256)),
                ('player_password', models.CharField(max_length=256)),
                ('player_verified', models.BooleanField(default=False)),
                ('player_character_model', models.CharField(default='new', max_length=256)),
                ('player_character_color', models.CharField(default='new', max_length=256)),
                ('player_key_bindings', models.TextField(default='new')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farcry.Player')),
            ],
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('one_time_token', models.BooleanField(default=False)),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farcry.Player')),
            ],
        ),
    ]
